### The price of a car depends on a lot of factors like the goodwill of the brand of the car,features of the car, horsepower and the mileage it gives and many more. Car priceprediction is one of the major research areas in machine learning. So if you want to learnhow to train a car price prediction model then this project is for you.

In [40]:
#import the standard librires
import pandas as pd,numpy as np,seaborn as sns,matplotlib.pyplot as plt
#import the sklearn librares
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
import math

In [42]:
df=pd.read_csv('car data.csv')
df.head(100)

Car_Name  Year  Selling_Price  Present_Price  Driven_kms Fuel_Type  \
0            ritz  2014           3.35           5.59       27000    Petrol   
1             sx4  2013           4.75           9.54       43000    Diesel   
2            ciaz  2017           7.25           9.85        6900    Petrol   
3         wagon r  2011           2.85           4.15        5200    Petrol   
4           swift  2014           4.60           6.87       42450    Diesel   
..            ...   ...            ...            ...         ...       ...   
95  corolla altis  2012           5.85          18.61       72000    Petrol   
96         innova  2016          20.75          25.39       29000    Diesel   
97  corolla altis  2017          17.00          18.64        8700    Petrol   
98  corolla altis  2013           7.05          18.61       45000    Petrol   
99       fortuner  2010           9.65          20.45       50024    Diesel   

   Selling_type Transmission  Owner  
0        Dealer       Manual      0  
1        Dealer       Manual      0  
2        Dealer       Manual      0  
3        Dealer       Manual      0  
4        Dealer       Manual      0  
..          ...          ...    ...  
95       Dealer       Manual      0  
96       Dealer    Automatic      0  
97       Dealer       Manual      0  
98       Dealer       Manual      0  
99       Dealer       Manual      0  

[100 rows x 9 columns]

In [6]:
#check the information of the datasett
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Driven_kms     301 non-null    int64  
 5   Fuel_Type      301 non-null    object 
 6   Selling_type   301 non-null    object 
 7   Transmission   301 non-null    object 
 8   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


In [7]:
#Describe function
df.describe().style.background_gradient(cmap='winter')

In [29]:
# Importing the necessary libraries
from sklearn.ensemble import RandomForestRegressor

# Create a Random Forest Regressor model
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Make predictions
rf_predictions = rf_model.predict(X_test)

# Calculate Mean Squared Error
rf_mse = mean_squared_error(y_test, rf_predictions)
print('Random Forest Mean Squared Error:', rf_mse)


Random Forest Mean Squared Error: 5.593809212926228


In [ ]:
Car.drop(["Unnamed: 0"],axis=1,inplace=True)
Car.drop(["max_power(bhp)"],axis=1,inplace=True)
Car=Car[~Car["registration_year"].str.isnumeric()]
Car=Car[Car["manufacturing_year"].str.isnumeric()]

In [45]:
# Importing the necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Load the dataset
df = pd.read_csv('car data.csv')

# Split the data into features and target variable
X = df[['Selling_Price', 'Present_Price', 'Driven_kms', 'Year']]
y = df['Owner']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions
predictions = model.predict(X_test)

# Calculate Mean Squared Error
mse = mean_squared_error(y_test, predictions)
print('Mean Squared Error:', mse)


Mean Squared Error: 0.02249017530777799


In [1]:
#loading the dataset
#import pandas library
import pandas as pd
#reading the data
df = pd.read_csv('car data.csv')

In [2]:
df.describe()

Year  Selling_Price  Present_Price     Driven_kms       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.642584   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [4]:
# Providing the input and output data
# importing numpy library
import numpy as np

In [5]:
#the input data (x, regressor)
x = np.array(df["Selling_Price"]).reshape(-1,1)

In [6]:
x.shape

(301, 1)

In [7]:
print(x)

[[ 3.35]
 [ 4.75]
 [ 7.25]
 [ 2.85]
 [ 4.6 ]
 [ 9.25]
 [ 6.75]
 [ 6.5 ]
 [ 8.75]
 [ 7.45]
 [ 2.85]
 [ 6.85]
 [ 7.5 ]
 [ 6.1 ]
 [ 2.25]
 [ 7.75]
 [ 7.25]
 [ 7.75]
 [ 3.25]
 [ 2.65]
 [ 2.85]
 [ 4.9 ]
 [ 4.4 ]
 [ 2.5 ]
 [ 2.9 ]
 [ 3.  ]
 [ 4.15]
 [ 6.  ]
 [ 1.95]
 [ 7.45]
 [ 3.1 ]
 [ 2.35]
 [ 4.95]
 [ 6.  ]
 [ 5.5 ]
 [ 2.95]
 [ 4.65]
 [ 0.35]
 [ 3.  ]
 [ 2.25]
 [ 5.85]
 [ 2.55]
 [ 1.95]
 [ 5.5 ]
 [ 1.25]
 [ 7.5 ]
 [ 2.65]
 [ 1.05]
 [ 5.8 ]
 [ 7.75]
 [14.9 ]
 [23.  ]
 [18.  ]
 [16.  ]
 [ 2.75]
 [ 3.6 ]
 [ 4.5 ]
 [ 4.75]
 [ 4.1 ]
 [19.99]
 [ 6.95]
 [ 4.5 ]
 [18.75]
 [23.5 ]
 [33.  ]
 [ 4.75]
 [19.75]
 [ 9.25]
 [ 4.35]
 [14.25]
 [ 3.95]
 [ 4.5 ]
 [ 7.45]
 [ 2.65]
 [ 4.9 ]
 [ 3.95]
 [ 5.5 ]
 [ 1.5 ]
 [ 5.25]
 [14.5 ]
 [14.73]
 [ 4.75]
 [23.  ]
 [12.5 ]
 [ 3.49]
 [ 2.5 ]
 [35.  ]
 [ 5.9 ]
 [ 3.45]
 [ 4.75]
 [ 3.8 ]
 [11.25]
 [ 3.51]
 [23.  ]
 [ 4.  ]
 [ 5.85]
 [20.75]
 [17.  ]
 [ 7.05]
 [ 9.65]
 [ 1.75]
 [ 1.7 ]
 [ 1.65]
 [ 1.45]
 [ 1.35]
 [ 1.35]
 [ 1.35]
 [ 1.25]
 [ 1.2 ]
 [ 1.2 ]
 [ 1.2 ]
 

In [8]:
#the input data (x, regressor)
y = np.array(df["Present_Price"])

In [9]:
y.shape

(301,)

In [10]:
print(y)

[ 5.59   9.54   9.85   4.15   6.87   9.83   8.12   8.61   8.89   8.92
  3.6   10.38   9.94   7.71   7.21  10.79  10.79  10.79   5.09   7.98
  3.95   5.71   8.01   3.46   4.41   4.99   5.87   6.49   3.95  10.38
  5.98   4.89   7.49   9.95   8.06   7.74   7.2    2.28   3.76   7.98
  7.87   3.98   7.15   8.06   2.69  12.04   4.89   4.15   7.71   9.29
 30.61  30.61  19.77  30.61  10.21  15.04   7.27  18.54   6.8   35.96
 18.61   7.7   35.96  35.96  36.23   6.95  23.15  20.45  13.74  20.91
  6.76  12.48  18.61   5.71   8.93   6.8   14.68  12.35  22.83  30.61
 14.89   7.85  25.39  13.46  13.46  23.73  92.6   13.74   6.05   6.76
 18.61  16.09  13.7   30.61  22.78  18.61  25.39  18.64  18.61  20.45
  1.9    1.82   1.78   1.6    1.47   2.37   3.45   1.5    1.5    1.47
  1.78   1.5    2.4    1.4    1.47   1.47   1.47   1.9    1.47   1.9
  1.26   1.5    1.17   1.47   1.75   1.75   0.95   0.8    0.87   0.84
  0.87   0.82   0.95   0.95   0.81   0.74   1.2    0.787  0.87   0.95
  1.2    0.8    0.84 

In [13]:
print(type(y))

<class 'numpy.ndarray'>


In [29]:
#splitting the dataset
#import train_test_split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.30)

In [30]:
#Eploring the train and testn datasets
x_train.shape

(210, 1)

In [40]:
x_train.shape

(210, 1)

In [41]:
x_test.shape

(91, 1)

In [42]:
y_train.shape

(210,)

In [43]:
y_test.shape

(91,)

In [44]:
#import library 
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,f1_score,recall_score,precision_score

In [45]:
feat_vect=TfidfVectorizer(min_df=1,stop_words='english',lowercase=True)
feat_vect

TfidfVectorizer(stop_words='english')

In [47]:
x_train,x_test

(array([[ 2.25],
        [ 9.15],
        [ 1.95],
        [ 0.48],
        [33.  ],
        [ 5.2 ],
        [ 8.25],
        [ 0.45],
        [ 7.4 ],
        [ 0.65],
        [ 3.5 ],
        [ 2.1 ],
        [ 4.4 ],
        [ 3.25],
        [ 0.75],
        [ 0.5 ],
        [ 0.9 ],
        [ 6.  ],
        [ 0.5 ],
        [ 5.15],
        [ 2.9 ],
        [ 5.65],
        [ 5.25],
        [ 1.95],
        [ 4.  ],
        [ 5.5 ],
        [ 7.75],
        [ 5.11],
        [ 9.25],
        [ 3.35],
        [ 1.2 ],
        [ 0.2 ],
        [ 3.  ],
        [ 2.75],
        [ 0.65],
        [ 8.5 ],
        [ 0.48],
        [ 5.95],
        [ 5.95],
        [ 6.7 ],
        [ 0.35],
        [ 6.45],
        [ 2.7 ],
        [ 0.5 ],
        [ 3.9 ],
        [ 7.9 ],
        [12.9 ],
        [ 0.9 ],
        [ 8.35],
        [ 3.95],
        [ 6.85],
        [ 4.6 ],
        [ 5.75],
        [ 6.25],
        [ 9.65],
        [ 4.75],
        [ 4.  ],
        [ 0.6 ],
        [ 0.45

In [48]:
y_train,y_test

(array([ 7.98 , 13.6  ,  7.15 ,  0.52 , 36.23 ,  9.4  ,  9.4  ,  0.51 ,
         8.5  ,  1.2  ,  5.43 ,  7.6  ,  8.01 ,  5.09 ,  0.8  ,  0.88 ,
         0.95 ,  8.4  ,  0.55 ,  5.7  ,  4.41 ,  7.9  ,  7.6  ,  3.95 ,
         5.8  ,  8.06 , 10.79 ,  9.4  ,  9.83 , 11.   ,  1.5  ,  0.65 ,
         5.35 , 10.21 ,  0.74 , 13.6  ,  0.54 ,  9.4  ,  9.4  , 10.   ,
         1.05 ,  8.4  ,  4.6  ,  0.99 ,  5.7  ,  8.1  , 13.6  ,  1.75 ,
         9.4  ,  6.8  , 10.38 ,  6.87 ,  7.13 , 13.6  , 20.45 ,  6.76 ,
        22.78 ,  0.84 ,  0.54 ,  7.85 , 10.   ,  0.95 , 23.73 ,  0.72 ,
         1.05 ,  9.94 ,  4.15 ,  1.6  ,  7.87 ,  7.2  ,  1.5  ,  7.74 ,
        13.6  , 18.61 ,  0.54 ,  0.73 ,  5.9  ,  9.9  ,  2.37 ,  1.47 ,
         0.87 ,  1.5  ,  0.55 ,  6.79 , 10.   , 20.45 ,  0.52 ,  7.71 ,
         5.59 ,  9.4  ,  5.71 , 14.89 ,  3.46 ,  9.29 ,  0.58 , 13.46 ,
         7.27 , 30.61 ,  0.83 ,  1.78 , 10.79 ,  2.28 , 18.61 ,  8.93 ,
         1.47 ,  0.84 , 23.15 ,  0.75 ,  0.787,  7.6  ,  0.99 , 

In [64]:
logi=LogisticRegression()
logi.fit(x_train,y_train)

C:\Users\Bhuli\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [65]:
logi.score(x_train,y_train)

logi.score(x_test,y_test)

pred_logi=logi.predict(x_test)
pred_logi

array([13,  7,  7,  9,  9,  1,  7, 13,  0,  1,  7,  1,  7, 13,  7,  0,  1,
        7,  0,  1,  0,  0,  9,  1,  9,  0,  0,  7,  7,  7,  1,  0,  0,  0,
        1,  0,  1,  7,  7,  7,  0,  7,  7, 30,  0, 30,  0,  0,  1, 13,  7,
        7,  0,  7,  0,  0,  7,  7,  7, 30,  7,  1,  0,  1, 13,  1,  0,  7,
        1,  0,  0,  7, 30,  7, 13,  0,  0, 13,  7,  9,  7,  1,  0,  0,  0,
        7,  9,  7,  0,  7,  9])

In [66]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
accuracy_score(y_test,pred_logi)

0.46153846153846156

In [68]:
confusion_matrix(y_test,pred_logi)

array([[27,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0],
       [ 1,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0],
       [ 0,  5,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  4,  0,  2,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,

In [69]:
print(classification_report(y_test,pred_logi))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        27
           1       0.40      0.86      0.55         7
           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00         8
           5       0.00      0.00      0.00         5
           6       0.00      0.00      0.00         6
           7       0.17      1.00      0.29         5
           8       0.00      0.00      0.00         2
           9       0.29      0.33      0.31         6
          10       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         2
          12       0.00      0.00      0.00         3
          13       0.29      0.40      0.33         5
          14       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         1
          18       0.00      0.00      0.00         2
          20       0.00      0.00      0.00         1
          22       0.00    

C:\Users\Bhuli\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Bhuli\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Bhuli\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
